language: php
php:
  - 5.4
  - 5.5

before_script:
  - mysql -uroot -e 'create database m5s_app;'
  - mysql -uroot m5s_app < data/dump.sql
  - php app/console fos:user:create admin admin@m5s.local admin --super-admin

script: phpunit -c app/

install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install -n

notifications:
  email: false

addon:
  hosts:
    api.m5s.local

