fos_user_security_login:
    pattern:    /oauth/v2/auth_login
    defaults:   { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern:    /oauth/v2/auth_login_check
    defaults:   { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    pattern:    %logout_pattern%
    defaults:   { _controller: FOSUserBundle:Security:logout }

cs_api_default:
    resource:   CsCloud\ApiBundle\Controller\DefaultController
    type:       rest

cs_api_user:
    resource:   CsCloud\ApiBundle\Controller\UserController
    type:       rest
