parameters:
#    cs_cloud_api.example.class: CsCloud\ApiBundle\Example

services:
#    cs_cloud_api.example:
#        class: %cs_cloud_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
