parameters:
    cs_cloud_api.logout_success_handler.class: CsCloud\ApiBundle\Security\LogoutSuccessHandler

services:
    cs_cloud_api.logout_success_handler:
        class: %cs_cloud_api.logout_success_handler.class%
        arguments:
            - "@security.http_utils"
            - "/"
