cs_cloud_frontend_homepage:
    pattern:  /
    defaults: { _controller: CsCloudFrontendBundle:Default:homepage }

cs_cloud_frontend_logout:
    pattern:  /logout

cs_cloud_frontend_hello:
    pattern:  /hello/{name}
    defaults: { _controller: CsCloudFrontendBundle:Default:index }

cs_cloud_frontend_odf:
    pattern:  /odf/{filename}
    defaults: { _controller: CsCloudFrontendBundle:Default:odf }
