parameters:
#    cs_cloud_frontend.example.class: CsCloud\FrontendBundle\Example

services:
#    cs_cloud_frontend.example:
#        class: %cs_cloud_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
