parameters:
    cs_cloud_frontend.logout_success_handler.class: CsCloud\FrontendBundle\Security\LogoutSuccessHandler

services:
    cs_cloud_frontend.logout_success_handler:
        class: %cs_cloud_frontend.logout_success_handler.class%
        arguments:
            - "@security.http_utils"
            - "@security.context"
            - "%logout_url%"
            - "/"
